### PR TITLE
Book  Recommendation  System 

### PR DESCRIPTION
**Pull request by SimranShaikh20**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
Issue no - #828 
- [x] I have provided the issue title.

---

#### Info about the Related Issue
New Project

The main objective of this project is to create a book recommendation system for users. Recommender systems are critical in many industries as they can generate significant income when efficient and provide a competitive advantage.

#### Name
**Please mention your name.**  
Simran Shaikh
- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
@SimranShaikh20 

- [x] I have provided my GitHub ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*Enter your participant role here.*
GSSOC '24 Extd
- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #issue-number*

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*Describe your changes here.*
Added folder to machine learning folder including all mandatory files.
- [x] I have described my changes.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SimranShaikh20** [comment]
@UTSAVS26 pls review pr and is there any changes let me know!
and pls change level you had assign because this is one entire project inlucding feature of recommendation system !

**Comment by UTSAVS26** [comment]
> @UTSAVS26 pls review pr and is there any changes let me know!
> and pls change level you had assign because this is one entire project inlucding feature of recommendation system !

Level should not be changed as you are adding project only.

**Comment by SimranShaikh20** [comment]
@UTSAVS26 pls merge PR!

**Comment by UTSAVS26** [comment]
@SimranShaikh20 branch has merge conflicts.

**Comment by SimranShaikh20** [comment]
@UTSAVS26 
Okay i will make new pr

**Pull request closed without merging**
