### PR TITLE
Enhance and Structure the Contributors Section

### PR DESCRIPTION
**Pull request by alo7lika**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
*Enhance and Structure the Contributors Section*

- [x] I have provided the issue title.

---

#### Info about the Related Issue
*The aim of the project is to create an organized and comprehensive contributors section that highlights the contributions of various developers in a visually appealing manner.*

- [x] I have described the aim of the project.

---

#### Name 
*Alolika Bhowmik*

- [x] I have provided my name.

---

#### GitHub ID
*alo7lika*

- [x] I have provided my GitHub ID.

---

#### Email ID
*alolikabhowmik72@gmail.com*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*GSSoC Contributor*

- [x] I have mentioned my participant role.

---

#### Closes
*Closes: #735 *

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
*I have enhanced the contributors section by structuring it with clear visuals, adding GitHub links, and ensuring it follows the repository's formatting guidelines.*

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
*I tested the contributors section on multiple devices and browsers to ensure it displays correctly and the links function as intended.*

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by alo7lika** [comment]
@ruhi47 , @shaansuraj, @TheChaoticor , @UTSAVS26  the task has been completed. Kindly Review it.

**Comment by UTSAVS26** [comment]
@alo7lika everytime when contributor contribute did they need to add their name and I'd themselves in the readme file or there is some workflows runs behind to add them automatically?

**Comment by alo7lika** [comment]
@UTSAVS26  made some changes. Kindly review it.

**Comment by alo7lika** [comment]
> @UTSAVS26 made some changes. Kindly review it.

@ruhi47 , @shaansuraj, @TheChaoticor

**Pull request merged**
