### PR TITLE
Ml Project Add

### PR DESCRIPTION
**Pull request by SimranShaikh20**
#### Issue Title
 Add Most Important Project for Today's era #615

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*Describe your changes here.*

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SimranShaikh20** [comment]
@UTSAVS26   check now i make new branch !

**Comment by SimranShaikh20** [comment]
@shaansuraj  can you please review PR!

**Comment by SimranShaikh20** [comment]
@UTSAVS26  is there any conflicts?

**Comment by UTSAVS26** [comment]
@SimranShaikh20 create a detailed readme file for the project.

**Review by SimranShaikh20 — COMMENTED** [review]
@UTSAVS26 added README.md file kindly review it !

**Comment by SimranShaikh20** [comment]
@UTSAVS26  can you pls change level  you had assigned as per work i had done !

**Pull request merged**
