### PR TITLE
Feat/fix 51: Display of the Pyverse repository  structure

### PR DESCRIPTION
**Pull request by yashksaini-coder**
# Pull Request for PyVerse 💡

## Issue Title : Display of the Pyverse repository

- **Info about the related issue (Aim of the project)** : 
- **Name:** Yash K. Saini
- **GitHub ID:** https://github.com/yashksaini-coder
- **Identify yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)** GSSOC-Ext contributor

Closes: #51 

### Describe the add-ons or changes you've made 📃

Documentation updates:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L73-R73): Removed the detailed repository structure and added a link to the new `Repo-structure.md` file.
* [`Repo-structure.md`](diffhunk://#diff-31c4b6951cbe74eeb2e8d9df82e60b2b071f3ff3455d1c38187207b3ed8a7617R1-R2): Added markers for the repository structure content.

Script updates:

* [`.github/scripts/update_dir_structure.py`](diffhunk://#diff-a3513e00160838e62e57ce600bce7b0601df6ea27e8f1f89c23109b06b3aca7dL25-R25): Updated the file name from `README.md` to `Repo-structure.md` in the `update_readme` function.

## Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
Hi @UTSAVS26 review this PR and add labels to this PR. Also dropped a msg on discord for a problem I don't know how to fix

**Comment by UTSAVS26** [comment]
> Hi @UTSAVS26 review this PR and add labels to this PR. Also dropped a msg on discord for a problem I don't know how to fix

Have you checked that the script is running correct or not?

**Comment by UTSAVS26** [comment]
@yashksaini-coder and please add the same contribution role as the issue, it don't need to be change

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder and please add the same contribution role as the issue, it don't need to be change

done

**Comment by yashksaini-coder** [comment]
I have ran this workflow action, in my forked version

image 

image

**Comment by yashksaini-coder** [comment]
All the actions workflow is working exactly fine.

**Review by UTSAVS26 — APPROVED** [review]

**Pull request merged**
