### PR TITLE
Count the number of zeroes#414

### PR DESCRIPTION
**Pull request by Ananya-vastare**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
*Enter the issue title here.*Count the number of zeroes

- [ X] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The goal of the project is to count the number of zeroes in a given integer using recurison

*Describe the aim of the project.*

The aim of the Counting Number of Zeroes project is to develop an algorithm and a program that efficiently counts the number of zeroes in a given number, which may be an integer or a floating-point value. The project focuses on handling different types of numeric input, including both positive and negative numbers, and ensuring accurate zero-counting, even in the presence of decimal points. This project helps in reinforcing concepts of recursion, string manipulation, and input validation while dealing with numeric data in various formats

- [ X] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Enter your name here.*Ananya Ravikiran Vastare

- [ X] I have provided my name.

---

#### GitHub ID:
**Please mention your GitHub ID.**  
*Enter your GitHub ID here.*Ananya-vastare

- [X ] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*Enter your email ID here.*ananyarvastare@gmail.com

- [ X] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*Enter your participant role here.*GSSOC

- [X ] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #issue-number* #414

- [X ] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*Describe your changes here.*
I have added a new code to the project
- [X ] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*Describe your testing process here.*

The changes have been tested through a comprehensive process that includes unit tests for various scenarios, such as positive and negative integers, positive and negative floats, and edge cases like 0, -0, and strings with no zeroes. Each test case was designed to verify the correct counting of zeroes, including manual testing where different inputs were entered to check for expected outputs and error handling for non-numeric values. Additionally, boundary testing was performed on edge cases and very large numbers to ensure robustness. The output was reviewed to confirm accuracy, and a code review with peers was conducted to ensure sound logic and adherence to best practices. This thorough approach validated the functionality of the counting zeroes algorithm, confirming it operates as expected across a variety of conditions.
- [X ] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [ X] My code follows the guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [X ] I have commented my code, particularly wherever it was hard to understand.
- [X ] I have made corresponding changes to the documentation.
- [X ] My changes generate no new warnings.
- [X ] I have added things that prove my fix is effective or that my feature works.
- [ X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
image
The logic has some error

**Comment by Ananya-vastare** [comment]
Okay will debug it and get back to you

**Comment by Ananya-vastare** [comment]
@UTSAVS26 I have modified it please check it and get back thank you

**Comment by Ananya-vastare** [comment]
@shaansuraj @TheChaoticor @UTSAVS26 may I please know that the code is working fine

**Comment by Ananya-vastare** [comment]
@UTSAVS26 @TheChaoticor without the previous pull request getting accepted I am not able to create a new one is that fine????

**Comment by UTSAVS26** [comment]
@TheChaoticor please check if the logic has been corrected or not, on urgent basis. 

@Ananya-vastare yes you can raise new issue and link this one there.

**Comment by Ananya-vastare** [comment]
@TheChaoticor I have checked the logic is it fine from your end

**Comment by Ananya-vastare** [comment]
@TheChaoticor any updates please

**Pull request merged**
