### PR TITLE
Added Data Science Project - Whatsapp Chat Analyzer

### PR DESCRIPTION
**Pull request by halcyon-past**
# Pull Request for PyVerse 💡

## Issue Title : 📃: Add Data Science Project - Whatsapp Chat Analyzer #142

- **Info about the related issue (Aim of the project)** : To Parse Real World Data and perform Exploratory Data Analysis on them and Provide the results in a web interface
- **Name:** Aritro Saha
- **GitHub ID:** halcyon-past
- **Email ID:** titanssuperior@gmail.com
- **Idenitfy yourself:** Contributor(GirlScript Summer of Code (GSSOC) 2024 - Extended Edition)

Closes: #142 

### Describe the add-ons or changes you've made 📃

1. Implemented a file upload feature to allow users to upload WhatsApp chat files (`.txt` or `.zip`).
2. Processed the uploaded chat data to extract relevant information using regular expressions.
3. Extracted details such as date, time, author, message content, and emojis.
4. Analyzed message data to calculate statistics like messages sent, average response time, word count, and emoji usage.
5. Visualized the extracted information using various charts such as pie charts, bar charts, and polar plots.
6. Generated a word cloud of the most frequently used words in the chat.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested? ⚙️

Manual Testing Has Been Performed

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by UTSAVS26 — COMMENTED** [review]
Can you add some samples of dataset, so that anyone can look and use them for testing purpose.

**Comment by halcyon-past** [comment]
okay sure will add them in a few moments

**Comment by halcyon-past** [comment]
Hey @UTSAVS26 I have added Sample data for testing

**Comment by UTSAVS26** [comment]
> Hey @UTSAVS26 I have added Sample data for testing

Great 👍

**Review by TheChaoticor — APPROVED** [review]

**Comment by halcyon-past** [comment]
@UTSAVS26 any updates regarding this pr?

**Pull request merged**
