### PR TITLE
added web resources

### PR DESCRIPTION
**Pull request by Charul00**
# Pull Request for PyVerse 💡

## Issue Title : Web Development Resources PDF

- **Info about the related issue (Aim of the project)** : The aim of this project is to provide a detailed PDF that compiles essential resources for learning web development. It includes tutorials, documentation, tools, and frameworks necessary for both beginners and advanced developers to enhance their web development skills.
- **Name:** Charul Chim
- **GitHub ID:** Charul00
- **Email ID:** charulchim@example.com
- **Identify yourself:** gssoc 2024 Participant

Closes: #134 

### Describe the add-ons or changes you've made 📃

I have added a comprehensive PDF document containing a curated list of web development resources. The PDF includes categories such as HTML, CSS, JavaScript, frontend frameworks (e.g., React, Vue), backend technologies (e.g., Node.js, Express), and tools for deployment and testing.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested all the links and references within the PDF to ensure they are active and provide relevant information. Additionally, the content was reviewed for clarity and usability.

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Charul00** [comment]
please merge now sir i correct it all thing @UTSAVS26

**Review by TheChaoticor — APPROVED** [review]

**Comment by Charul00** [comment]
can you please merge it @UTSAVS26

**Comment by Charul00** [comment]
@UTSAVS26 please approve 
@shaansuraj  please approve

**Review by UTSAVS26 — APPROVED** [review]

**Comment by Charul00** [comment]
@shaansuraj please can you approve please 
and merge it guys

**Pull request merged**
