### PR TITLE
added code and dataset

### PR DESCRIPTION
**Pull request by AKSHITHA-CHILUKA**
# Pull Request for PyVerse 💡

## Issue Title : #33 

- **Info about the related issue (Aim of the project)** : add documents related to ml
- **Name:** Akshitha
- **GitHub ID:** AKSHITHA-CHILUKA
- **Email ID:** chiluka.akshitha05@gmail.com
- **Idenitfy yourself: ** gssoc,hactoberfest

Closes: #33 

### Describe the add-ons or changes you've made 📃

So I have added the code how to scrape the data using selenium , This code help to get the data from 1mg website ,also the dataset which I have scraped 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@AKSHITHA-CHILUKA please fill all the details in the Templates along with checkboxes which have you completed.

**Comment by UTSAVS26** [comment]
> done @UTSAVS26 

What about the 
```
Info about the related issue (Aim of the project) :
Name:
GitHub ID:

Describe the add-ons or changes you've made 📃
Give a clear description of what have you added or modifications made
```
🥲

**Comment by AKSHITHA-CHILUKA** [comment]
sorry @UTSAVS26 done it now

**Comment by UTSAVS26** [comment]
> sorry @UTSAVS26 done it now

Okie 👍

**Review by UTSAVS26 — APPROVED** [review]

**Review by TheChaoticor — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
can you also add gssoc lable

**Comment by TheChaoticor** [comment]
> can you also add gssoc lable

It's a gssoc ext project

**Pull request merged**
