### PR TITLE
Added a file Decision Tree Classifier in the machine learning folder

### PR DESCRIPTION
**Pull request by Shreya7tripathy**
## Issue Title : **Customer Purchase Prediction using Decision Tree Classifier**

- **Info about the related issue (Aim of the project)**: The goal of the project is to develop a Decision Tree Classifier to predict whether a customer will purchase a product or service based on demographic and behavioral data. The dataset used is the Bank Marketing dataset from the UCI Machine Learning Repository.
- **Name**: Shreya Tripathy
- **GitHub ID**: [Shreya7tripathy](https://github.com/Shreya7tripathy)
- **Email ID**: shreya7tripathy@gmail.com
- **Identify yourself**: gssoc-ext , hacktoberfest-accepted  , contributer

Closes: Issue #131 that will be closed after this PR is merged 

### Describe the add-ons or changes you've made 📃

I have added a 'Decision Tree Classifier 'implementation for the Customer Purchase Prediction project in the `machinelearning` folder of the project repository. Additionally, I included a detailed `README.md` to explain the project structure and added the dataset required for the project.

## Type of change ☑️

What sort of change have you made:
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

- The changes have been tested by training and evaluating the Decision Tree Classifier using the Bank Marketing dataset. 
- The model's performance was validated using metrics such as accuracy, precision, recall, and F1-score. 
- Additional manual testing has been done to verify the functionality and ensure that there are no issues with the implementation.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by TheChaoticor** [comment]
image
Please rename according to your description and definition in the code

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
read the above comment written by me

**Comment by Shreya7tripathy** [comment]
> image Please rename according to your description and definition in the code

OK OK SURE.LET ME FIX THIS

**Comment by Shreya7tripathy** [comment]
Updated the file check once @TheChaoticor .

**Comment by TheChaoticor** [comment]
> Updated the file check once @TheChaoticor .

I approve the changes ,let @UTSAVS26 review it. I liked the idea of adding heatmap

**Review by UTSAVS26 — APPROVED** [review]

**Pull request merged**
