### PR TITLE
Added sorting techniques in data structure and algorithms

### PR DESCRIPTION
**Pull request by rugved0102**
# Pull Request for PyVerse 💡

## Issue Title : Adding sorting Techniques in Data Structure and Algorithms

- **Info about the related issue (Aim of the project)** : To explore sorting techniques in DSA
- **Name:** Rugved
- **GitHub ID:** rugved0102 
- **Email ID:** rugved@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)** GSSOC, Hacktoberfest 

Closes: #165 

### Describe the add-ons or changes you've made 📃
Added a sort.py in which i have added sorting techniques like merge sort, bubble sort etc.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@rugved0102 please add all the asked details in the PR template.

**Comment by rugved0102** [comment]
@UTSAVS26 can you please check once ? I have done the changes.

**Comment by UTSAVS26** [comment]
Based on the work you have given you are gonna do, I don't think I am able to see, as you have told that 
`different sorting algorithms, their time complexities, and use cases. Sorting techniques like QuickSort, MergeSort, BubbleSort, SelectionSort, and InsertionSort will be implemented, and their working principles explained. Each algorithm will be accompanied by code examples and performance analysis.`

I can only able to see 1 file. Not any documentation, test cases, performance analysis and all the sorting in one file.

**Comment by rugved0102** [comment]
@UTSAVS26  I have added sorting.md file in which I have given desc, time complexities and use cases of each sorting technique.

**Comment by UTSAVS26** [comment]
@rugved0102 if i suggest some changes then you need to add proper codes for each of the sorting algorithms separately and based on create their performance analysis graphs and detailed readme for each of them.

**Comment by rugved0102** [comment]
So I have to create separate file for each algo with code, desc, time complexity analysis/ performance graphs right ? If you have any more improvements please suggest me @UTSAVS26 .

**Comment by UTSAVS26** [comment]
> So I have to create separate file for each sorting technique with code, desc, time complexity analysis/ performance graphs right ? If you have any more improvements please suggest me @UTSAVS26 .

Right now only these ones. Based on the work done I can suggest some more or approve it.

**Comment by UTSAVS26** [comment]
For now i am closing this PR. So that toh can have enough time to work on it.

**Comment by rugved0102** [comment]
Yes, Thank You. I will update soon.

**Comment by rugved0102** [comment]
https://github.com/rugved0102/PyVerse/tree/sorting-techniques-dsa/Algorithms_and_Data_Structures/Sorting%20Algorithms

can u check once @UTSAVS26 ? any more suggestions ??

**Comment by UTSAVS26** [comment]
> https://github.com/rugved0102/PyVerse/tree/sorting-techniques-dsa/Algorithms_and_Data_Structures/Sorting%20Algorithms
> 
> can u check once @UTSAVS26 ? any more suggestions ??

Try to add graphs comparing different cases like best, average and worst like sorted list, unsorted and all.

**Comment by rugved0102** [comment]
You mean time complexity graphs, right ?

**Pull request closed without merging**
