### PR TITLE
Added project "Autofill Personal Info Using Adhaar Card Image" under automation category. 

### PR DESCRIPTION
**Pull request by Mayank202004**
# Pull Request for PyVerse 💡

## Issue Title : Autofill Personal Info Using Aadhar Card Image

- **Info about the related issue (Aim of the project)** : To reduce manual work of typing personal details while applying for any online application that requires adhaar card ex. scholarships etc.
- **Name:** Mayank Sachin Chougale
- **GitHub ID:** Mayank202004
- **Email ID:** mayank.chougale20@gmail.com
- **Idenitfy yourself:**  GSSOC EXT

Closes: #111 

### Describe the add-ons or changes you've made 📃

Added complete project files

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Tested on few Aadhar cards using API created

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by UTSAVS26 — CHANGES_REQUESTED** [review]
Please check the files you have given in the PR once as some files don't have any format and remove `__pycache__` files 
Please add readme file of this [format](https://github.com/UTSAVS26/PyVerse/blob/main/.github%2Freadme_template.md).

**Comment by Mayank202004** [comment]
Check now

**Comment by Mayank202004** [comment]
why is the Repo-structure not updating itself? help me

**Comment by UTSAVS26** [comment]
> why is the Repo-structure not updating itself? help me

It will update automatically don't worry about it.

**Comment by UTSAVS26** [comment]
Just sync your repo.

**Comment by Mayank202004** [comment]
Can sync currently as my fork is some commits ahead

**Comment by Mayank202004** [comment]
Screenshot 2024-10-07 205756
discard then sync ?

**Comment by Mayank202004** [comment]
@UTSAVS26 Please verify

**Pull request merged**
