### PR TITLE
added web development resources 

### PR DESCRIPTION
**Pull request by Charul00**
# Pull Request for PyVerse 💡

## Issue Title : Web Development Resources PDF

- **Info about the related issue (Aim of the project)** : The aim of this project is to provide a detailed PDF that compiles essential resources for learning web development. It includes tutorials, documentation, tools, and frameworks necessary for both beginners and advanced developers to enhance their web development skills.
- **Name:** Charul Chim
- **GitHub ID:** Charul00
- **Email ID:** charulchim@example.com
- **Identify yourself:** gssoc 2024 Participant

Closes: #134 

### Describe the add-ons or changes you've made 📃

I have added a comprehensive PDF document containing a curated list of web development resources. The PDF includes categories such as HTML, CSS, JavaScript, frontend frameworks (e.g., React, Vue), backend technologies (e.g., Node.js, Express), and tools for deployment and testing.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested all the links and references within the PDF to ensure they are active and provide relevant information. Additionally, the content was reviewed for clarity and usability.

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Charul00** [comment]
@UTSAVS26 check now

**Comment by UTSAVS26** [comment]
@Charul00 there is some flaws in the folder names please recheck it once

Like 
`Web_Development/Web_Developement_resources/A _Proposed_Methodology_for_Web_Development.pdf`
Space is coming in between

And 
`Web_Development/Web_Developement_resources/25_Years_of_Model_Driven_Web_ Engineering_What_we_Achieved_What_is_Missing_Author_Gustavo_Rossi_Matias_Urbieta_Damiano_Distante.pdf`
In this too. 

And create a readme file for all the books altogether telling about all books.

**Comment by TheChaoticor** [comment]
@Charul00 please do not close the issue without permission. Your pull request was closed.Do not worry,i opened it.We will review it and get back to you

**Comment by Charul00** [comment]
@TheChaoticor i have created another pr with solving all reviews

**Comment by TheChaoticor** [comment]
Is it not this one?

**Comment by Charul00** [comment]
this is different one
i have mentioned the issue no so that i close this

**Comment by TheChaoticor** [comment]
You should have mentioned the same. Mention the issue no and pr link and i will close this one

**Comment by Charul00** [comment]
ok

**Comment by Charul00** [comment]
i mentioned already

**Comment by Charul00** [comment]
check pr no:#190

**Pull request closed without merging**
