### PR TITLE
Added  Chat-GPT-Discord-Bot advanced project

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The goal of this project is to create a Discord bot powered by GPT (Generative Pre-trained Transformer) that can interact with users in a Discord server, providing intelligent and natural language responses to user queries. The bot can be used for a wide variety of purposes including answering questions, engaging in conversations, and even providing automated customer support or assistance in Discord communities.

*Describe the aim of the project.*
Real-time Interaction: The bot should process user messages in real-time and provide relevant responses.
Seamless Integration: The bot needs to integrate smoothly into the Discord ecosystem, making use of Discord's API.
User-friendly Setup: Users should be able to easily add the bot to their servers, with simple commands and clear documentation.

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Abhijit Motekar*

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*AbhijitMotekar99*

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*motekarabhijit2@gmail.com*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*`gssoc-ext` `Hacktoberfest`*

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #670 *

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*Added Chat GPT Discord bot in Advanced project directory*

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*I describe all testing process in README.md in*

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@AbhijitMotekar99 don't add other files that are not related to the issue, it will cause not accepting or merging your PR.

**Comment by AbhijitMotekar99** [comment]
Ok I will remove it

**Comment by AbhijitMotekar99** [comment]
Hey @UTSAVS26 
I removed other files Now you can merged it

**Comment by UTSAVS26** [comment]
@AbhijitMotekar99 add more detailed README.md file and tell each and every details and steps how to get
```
BOT_TOKEN = "TOKEN_HERE"
OWNER_ID = "OWNER_UID_HERE"
GPT_API_KEY = "CHAT_GPT_API_KEY_HERE"
DISCORD_SERVER_1 = "FIRST_DISCORD_SERVER_ID_HERE"
DISCORD_SERVER_2 = "SECOND_DISCORD_SERVER_ID_HERE"
```

all of these 
and also add proper images and change the file paths

**Comment by AbhijitMotekar99** [comment]
Hey @UTSAVS26 
I added All Info in readme.md and Also added about how to get This
BOT_TOKEN = "TOKEN_HERE"
OWNER_ID = "OWNER_UID_HERE"
GPT_API_KEY = "CHAT_GPT_API_KEY_HERE"
DISCORD_SERVER_1 = "FIRST_DISCORD_SERVER_ID_HERE"
DISCORD_SERVER_2 = "SECOND_DISCORD_SERVER_ID_HERE"

**Comment by UTSAVS26** [comment]
> Hey @UTSAVS26 
> I added All Info in readme.md and Also added about how to get This
> BOT_TOKEN = "TOKEN_HERE"
> OWNER_ID = "OWNER_UID_HERE"
> GPT_API_KEY = "CHAT_GPT_API_KEY_HERE"
> DISCORD_SERVER_1 = "FIRST_DISCORD_SERVER_ID_HERE"
> DISCORD_SERVER_2 = "SECOND_DISCORD_SERVER_ID_HERE"

Okie let me check it once.

**Comment by AbhijitMotekar99** [comment]
## Here You can see I added all steps with images To get required Key's.

https://github.com/user-attachments/assets/ebaac499-d41c-4bbe-b254-f4cc2489ab41

**Pull request merged**
