### PR TITLE
Updated Name Key Bindings (Hand Game Controller)

### PR DESCRIPTION
**Pull request by aviralgarg05**
Updated Names for Key Bindings
Solving #96 #115

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@aviralgarg05 use underscore rather than space and also update the code too, where we need to provide the image path.

**Comment by aviralgarg05** [comment]
Ok I will make the changes

**Comment by UTSAVS26** [comment]
@aviralgarg05 I have added some review comments please do that faster.

**Comment by aviralgarg05** [comment]
Comments aren't visible. Can you guide about it

**Comment by UTSAVS26** [comment]
@aviralgarg05 now you can see?

**Comment by aviralgarg05** [comment]
Yeah ok I will do the changes

**Comment by UTSAVS26** [comment]
> Yeah ok I will do the changes 

Okie

**Review by UTSAVS26 — APPROVED** [review]

**Comment by UTSAVS26** [comment]
@TheChaoticor please review it once.

**Review by TheChaoticor — APPROVED** [review]

**Pull request merged**
