### PR TITLE
Movie classification issue #152

### PR DESCRIPTION
**Pull request by praveenarjun**
# Pull Request for PyVerse 💡

## Issue Title : Movie Genre Classification Feature Implementation 🎬📽️ #152

- **Info about the related issue (Aim of the project)** : 
- **Name:** Sree Praveen challa
- **GitHub ID:** praveenarjun
- **Email ID:** E22CSEU0171@bennett.edu.in
- **Idenitfy yourself: Gssoc Ext,Hackbefest

Closes: #152 

### Describe the add-ons or changes you've made 📃

I add a File in MAchine Learning folder-> Movie Classification->Movie classification.ipynb && readme file 

## Type of change ☑️

What sort of change have you made:

-  New feature (non-breaking change which adds functionality)
-  Breaking change (fix or feature that would cause existing functionality to not work as expected)
-  This change requires a documentation update:
  Yes I added Readme file so that User can Understand much better way

## How Has This Been Tested? ⚙️

Screenshot 2024-10-06 at 12 51 37 PM

Describe how it has been tested : Just run it on google colab 
Describe how have you verified the changes made

## Checklist: ☑️

- [Yes ] My code follows the guidelines of this project.
- [ Yes] I have performed a self-review of my own code.
- [ Yes] I have commented my code, particularly wherever it was hard to understand.
- [Yes ] I have made corresponding changes to the documentation.
- [ Yes] My changes generate no new warnings.
- [ Yes] I have added things that prove my fix is effective or that my feature works.
- [ Yes] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by UTSAVS26 — CHANGES_REQUESTED** [review]
Please add readme file of this [format](https://github.com/UTSAVS26/PyVerse/blob/main/.github%2Freadme_template.md).
And don't add spaces in the name of the file.

**Comment by praveenarjun** [comment]
I made the changes as you said I updated the readme file

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
image
Add the file on which you are training the model

**Comment by praveenarjun** [comment]
Ok I added the dataset so you can recheck again

**Pull request merged**
