### PR TITLE
Plagiarism checker Python

### PR DESCRIPTION
**Pull request by devxMani**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title #712 done
**Please enter the title of the issue related to your pull request.**  
*Enter the issue title here.* Plagiarism checker Python

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
*Describe the aim of the project.*

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Enter your name here.* Mani

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*Enter your GitHub ID here.* devxMani

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*Enter your email ID here.* chandramanigupta2003@gmail.com

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*Enter your participant role here.* GSSOC ext 24

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #712 *

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*Describe your changes here.* added the project

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*Describe your testing process here.*

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ruhi47** [comment]
Hey @devxMani , Please mention the #issue-number it solves. The PR comment has no exact issue number. Thanks!

**Comment by devxMani** [comment]
@ruhi47 I have mentioned that 
![image](https://github.com/user-attachments/assets/e86f7a17-1afc-4f3d-83ac-148fb399b559
@UTSAVS26 merge this PR

**Comment by ruhi47** [comment]
Screenshot 2024-10-24 at 7 18 09 PM
 I dont see it here, please read through again.

**Comment by devxMani** [comment]
@ruhi47 done

**Comment by UTSAVS26** [comment]
@devxMani remove cryptotracker project i am not allowing projects that don't have python integrated in them.

**Pull request merged**
