### PR TITLE
completed api for book-store-management

### PR DESCRIPTION
**Pull request by ojhankit**
# Pull Request for PyVerse 💡

## Issue Title : <API for book-store-management>

- **Info about the related issue (Aim of the project)** : To create an api for book-store-management
- **Name:** Ankit Ojha
- **GitHub ID:** ojhankit
- **Email ID:** <ojha27ankit@gmail.com>
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)** 
gssoc-ext

Closes: #108 

### Describe the add-ons or changes you've made 📃
create Book model added CRUD operation for 
creating book
reading list of book
updating book details
deleting book

added comments ,requirements file and how to get started with this project 
## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Tested endpoints using Postman

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ojhankit** [comment]
@UTSAVS26 please do review

**Comment by ojhankit** [comment]
@TheChaoticor @UTSAVS26  please do review.. do I have to make any changes?

**Comment by UTSAVS26** [comment]
> @TheChaoticor @UTSAVS26  please do review.. do I have to make any changes?

Let's wait until mentor @TheChaoticor approve.

**Comment by ojhankit** [comment]
okay..

**Comment by UTSAVS26** [comment]
@TheChaoticor and @shaansuraj check this PR.

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
image
There is some error in your path or related errors ,please check

**Comment by ojhankit** [comment]
@TheChaoticor Thanks for reviewing my code ..you have not written endpoints correctly also i have added comments on how to test api for ease.

**Comment by TheChaoticor** [comment]
> @TheChaoticor Thanks for reviewing my code ..you have not written endpoints correctly also i have added comments on how to test api for ease.

Ok let me check

**Comment by ojhankit** [comment]
@TheChaoticor any further changes required?

**Comment by ojhankit** [comment]
@TheChaoticor have you checked?

**Pull request merged**
