### PR TITLE
Added Web Scrapping Project in Machine_Learning

### PR DESCRIPTION
**Pull request by AmanPathan**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Added Web Scrapping Project in Machine_Learning**  

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
*Scrapping information related to a product listed on E-Commerce Website like Flipkart or Amazon using Python*

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Aman Pathan*

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*AmanPathan*

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*amanpathan526@gmail.com*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*GSSOC and hacktoberfest*

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #412 *

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*I have added a new ML project in Machine_Learning folder. It's a web scrapper used to collect information related to a product on Flipkart or Amazon.*

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*The code is written in Jupyter Notebook and it is working properly and doesn't generate any errors.*

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@AmanPathan where is the issue number that has been asked?

**Comment by AmanPathan** [comment]
> @AmanPathan where is the issue number that has been asked?

I have updated the issue number in the above comment and here -
Closes #412

**Comment by UTSAVS26** [comment]
@AmanPathan why is that you raised a PR before and then issue?

**Comment by AmanPathan** [comment]
It doesn't matter whether we raise the issue first or PR. I did so because you asked for the issue number related to my PR. So, I raised an issue and assigned my previous PR to solve it.

**Comment by UTSAVS26** [comment]
> It doesn't matter whether we raise the issue first or PR. I did so because you asked for the issue number related to my PR. So, I raised an issue and assigned my previous PR to solve it.

It matters
Raising an issue first helps ensure the problem is clearly identified and agreed upon before submitting a PR. 
If we don’t raise the issue first, it can lead to confusion, especially if someone else has already raised a similar issue. If we assign that issue to another contributor, their work and effort could overlap with what you’ve proposed in your PR, which may result in unnecessary duplication of work.
Raising an issue first allows us to check if the problem you’re addressing in your PR has already been resolved or assigned to someone else.

**Comment by UTSAVS26** [comment]
@AmanPathan sorry but I am not accepting this PR and also the issue. You can contribute more if you want to buy first raise issue then if maintainers assign the issue to you then raise a PR. You can read our discussion announcements section for more contributing guidelines.

**Comment by AmanPathan** [comment]
okay, thank you for the information. Let me create an issue first and then I will make a PR for that issue. Thank You!

**Pull request closed without merging**
