### PR TITLE
fix: 🐛 Fixed Auto comment workflow issues

### PR DESCRIPTION
**Pull request by yashksaini-coder**
## Issue Title : Auto comment on PR-merged & Issue-closed

- **Info about the related issue (Aim of the project)** : 
- **Name:** Yash K. Saini
- **GitHub ID:** [GitHub ID](https://github.com/yashksaini-coder)
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)** 
- **WoB'24 participant**

✅ Closes: #6

### Describe the add-ons or changes you've made 📃

This pull request includes updates to GitHub Actions workflows to improve consistency and fix minor issues. The most important changes include renaming a workflow, updating permissions, and fixing environment variable usage.

## Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

NA

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

@UTSAVS26 Review the PR & add labels `Level3` to it.

### CODE REVIEW

**Review by UTSAVS26 — APPROVED** [review]

**Comment by yashksaini-coder** [comment]
hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me

**Comment by UTSAVS26** [comment]
> hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me

Sorry bro, but this PR will be merged before WoB merging into GSSOC so i can't be able to add it now.

**Comment by yashksaini-coder** [comment]
> > hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me
> 
> Sorry bro, but this PR will be merged before WoB merging into GSSOC so i can't be able to add it now.

no you can as your project is in gssoc now @UTSAVS26

**Comment by UTSAVS26** [comment]
> > > hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me
> > 
> > 
> > Sorry bro, but this PR will be merged before WoB merging into GSSOC so i can't be able to add it now.
> 
> no you can as your project is in gssoc now @UTSAVS26

let me confirm it onces

**Pull request merged**
