### PR TITLE
Add Advanced Project - EDUHELPER

### PR DESCRIPTION
**Pull request by halcyon-past**
# Pull Request for PyVerse 💡

## Issue Title : 📃: Add Advanced Project - EDUHELPER

- **Info about the related issue (Aim of the project)** : To introduce GenAI and RAG and help students to get answers fast from their study materials
- **Name:** Aritro Saha
- **GitHub ID:** halcyon-past
- **Email ID:** titanssuperior@gmail.com
- **Idenitfy yourself:** Contributor(GirlScript Summer of Code (GSSOC) 2024 - Extended Edition)

Closes: #98 

### Describe the add-ons or changes you've made 📃

1. Set up a Streamlit interface to upload PDF files.
2. Created a function (`get_pdf_text`) to extract text from the uploaded PDF files using PyPDF2.
3. Split the extracted text into smaller chunks (`get_text_chunks`) for efficient retrieval.
4. Created a vector store (`get_vector_store`) using FAISS indexing and Google Generative AI embeddings to store the text chunks.
5. Set up a conversational chain (`get_conversational_chain`) to process questions and provide answers using Google's Generative AI API.
6. Developed the user interaction flow, where users can enter questions to receive relevant answers from the uploaded content.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested? ⚙️

Manual Testing Has Been Performed

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by UTSAVS26 — APPROVED** [review]

**Comment by UTSAVS26** [comment]
Waiting for mentors to review, if any one of them approve then merge

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
Add comments as it is an open source project and tho i admire the clean code, some comments at necessary areas would be good

**Comment by halcyon-past** [comment]
Sure will be working on that right now

**Comment by halcyon-past** [comment]
@TheChaoticor I have added comments to make the code more readable

**Review by TheChaoticor — APPROVED** [review]
Good Work

**Pull request merged**
