### PR TITLE
Bug-fix (README)

### PR DESCRIPTION
**Pull request by yashksaini-coder**
# Pull Request for DL-Simplified 💡

## Issue Title : README (Bug fix)

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)** 

### Wob'24 Contributor

Closes: #2 

### Describe the add-ons or changes you've made 📃
Removed the emoji symbols & rewrite the index and sections headings in correct markdown syntax.

---

## Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

## How Has This Been Tested? ⚙️

I preview the changes made to the readme from my forked copy. below is an attached gif of the changes being tested.

README-fix

---

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@UTSAVS26 I created a branch to fix the readme smooth transition. I also revert a commit due to some fixes I missed behind. 
but there are no error raised by my chnages.

Review the changes and add labels to this PR. 

- Also can you assign the other issue from tomorrow.

**Comment by yashksaini-coder** [comment]
hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me

**Comment by UTSAVS26** [comment]
> hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me

Sorry bro, but this PR will be merged before WoB merging into GSSOC so i can't be able to add it now.

**Comment by yashksaini-coder** [comment]
> > hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me
> 
> Sorry bro, but this PR will be merged before WoB merging into GSSOC so i can't be able to add it now.

also add for this one too @UTSAVS26

**Pull request merged**
