### PR TITLE
Add stack implementation with stack.py and readme.me

### PR DESCRIPTION
**Pull request by Charul00**
Pull Request for PyVerse 💡
Issue Title: Implement Stack Data Structure
Info about the related issue (Aim of the project): This project aims to implement a stack data structure using Python, providing essential operations such as push, pop, peek, and is_empty. The stack will be demonstrated through a practical implementation, enhancing understanding of LIFO (Last In First Out) behavior in data structures.

Name: Charul Chim

GitHub ID: Charul00

Email ID: charulchim18@gmail.com

Identify yourself: gssoc-ext contributor

Closes: #14 

Describe the add-ons or changes you've made 📃
In this pull request, I have created a stack folder that contains:

stack.py: This file implements the stack data structure with methods to perform push, pop, peek, and check if the stack is empty.
README.md: This file provides an overview of the stack data structure, its properties, and a guide on how to use the implemented code. It also includes explanations for the various methods in the stack.py file, making it easier for users to understand the implementation.
Type of change ☑️
What sort of change have you made:

 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)
 Code style update (formatting, local variables)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 This change requires a documentation update
How Has This Been Tested? ⚙️
The stack implementation has been tested by performing a series of push and pop operations to ensure the Last In First Out (LIFO) property is maintained. Each method has been invoked with various inputs to validate functionality, and the results have been printed for verification.

Checklist: ☑️
 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly wherever it was hard to understand.
 I have made corresponding changes to the documentation.
 My changes generate no new warnings.
 I have added things that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@Charul00 please add the correct issue

**Comment by Charul00** [comment]
> @Charul00 please add the correct issue

i have added check please

**Comment by TheChaoticor** [comment]
add a test/example for checking if and how the stack works for different data types

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
add a test/example for checking if and how the stack works for different data types

**Comment by Charul00** [comment]
> add a test/example for checking if and how the stack works for different data types

in readme file right?

**Comment by TheChaoticor** [comment]
no,in the code.  Add a simple test/example of atleast two different data types and try with strings too and comment its output

**Comment by Charul00** [comment]
> no,in the code. Add a simple test/example of atleast two different data types and try with strings too and comment its output

done please check now

**Comment by TheChaoticor** [comment]
merged,good work

**Pull request merged**
