### PR TITLE
added all the required files

### PR DESCRIPTION
**Pull request by AKSHITHA-CHILUKA**
# Pull Request for PyVerse 💡

## Issue Title : #22

- **Info about the related issue (Aim of the project)** : <add documents related to trees>
- **Name:** <Akshitha>
- **GitHub ID:** <AKSHITHA-CHILUKA>
- **Email ID:** <chiluka.akshitha05@gmail.com>
- **Idenitfy yourself: ** <gssoc,hactoberfest>

Closes: #22

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by UTSAVS26 — CHANGES_REQUESTED** [review]
please add comments in the code too in this format

def <function_name>(<parameters>):
   
    <Brief description of the function's purpose.>

    Args:
        <parameter_name> (<parameter_type>): <Description of the parameter.>

    Returns:
        <return_type>: <Description of the return value.>

    Example:
        >>> <function_name>(<example_input>)
        <example_output>
   
    # Function logic here

**Comment by AKSHITHA-CHILUKA** [comment]
Oh great First I have added the comments but I thought no need so I sent without commenting I will send it now as I already have the code with comments

**Review by AKSHITHA-CHILUKA — COMMENTED** [review]
added comments

**Comment by UTSAVS26** [comment]
@AKSHITHA-CHILUKA in the issue you have these 3 code files too
```
Menu_Driven_Code_for_Inorder_Traversal.py Menu_Driven_Code_for_Preorder_Traversal.py Menu_Driven_Code_for_Postorder_Traversal.py
```

What about these files?

**Comment by AKSHITHA-CHILUKA** [comment]
I have added those in Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_Tree_Traversals.py

**Comment by UTSAVS26** [comment]
> I have added those in Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_Tree_Traversals.py

Okie

**Pull request merged**
