### PR TITLE
Sentiment analysis using machine learning 

### PR DESCRIPTION
**Pull request by Ananya-vastare**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Related Issue:**  
#452 Sentiment analysis

- [X] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
To automatically identify and classify human emotions expressed in text.

**Aim of the project:**
1. Accurately detect and categorize sentiment and specific emotions.
2. Identify trends and patterns in emotions over time or demographics.
3. Provide real-time feedback for actionable insights.
4. Visualize results in an easy-to-understand format for decision-making.

- [X] I have described the aim of the project.

---

#### Your Information
**Name:**  
Ananya Ravikiran Vastare

- [X] I have provided my name.

**GitHub ID:**  
@Ananya-vastare

- [X] I have provided my GitHub ID.

**Email ID:**  
ananyarvastare@gmail.com

- [X] I have provided my email ID.

**Program:**  
GSSOC extd, Hacktoberfest

- [X] I have mentioned my participant role.

---

#### Issue Reference
**Closes:**  
Closes: #452

- [X] I have provided the issue number.

---

#### Description of Changes
**Add-ons or Modifications:**  
Implemented a sentiment analysis model to classify text data by identifying emotions. Added real-time processing for immediate insights and designed a visual dashboard to display sentiment trends. Enhancements include:
- Fine-tuning the model for higher accuracy across various emotions.
- Integrating user feedback for adaptive learning.
- Optimizing the interface for seamless interaction.

These changes aim to create a more responsive, accurate, and visually engaging sentiment analysis tool tailored to user needs.

- [X] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)  
- [X] New feature (non-breaking change which adds functionality)  
- [X] Code style update (formatting, local variables)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] This change requires a documentation update  

---

#### Testing Information
**Testing Process:**  
The changes were tested using a dataset with labeled emotions to evaluate model accuracy across different sentiment classes. Real-time analysis was validated with live input to ensure responsiveness. The dashboard was tested for usability and clarity through user feedback sessions.

- [X] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [X] My code follows the guidelines of this project.  
- [X] I have performed a self-review of my own code.  
- [X] I have commented my code, particularly wherever it was hard to understand.  
- [X] I have made corresponding changes to the documentation.  
- [X] My changes generate no new warnings.  
- [X] I have added elements that prove my fix is effective or that my feature works.  
- [ ] Any dependent changes have been merged and published in downstream modules.

---

Change2

### CODE REVIEW

**Comment by Ananya-vastare** [comment]
@ruhi47 @UTSAVS26 please let me know if I need to make any changes

**Comment by Ananya-vastare** [comment]
@UTSAVS26 @ruhi47 @shaansuraj please let me know if I need to make any changes

**Comment by UTSAVS26** [comment]
@Ananya-vastare move the project in the dedicated folder and remove `__pycache__` file.

**Comment by Ananya-vastare** [comment]
@UTSAVS26 I have done the changes please let me know if anythiing else has to be done

**Comment by Ananya-vastare** [comment]
@UTSAVS26 any updates please

**Comment by UTSAVS26** [comment]
@Ananya-vastare raise new PR as in this one there is no file.

**Pull request closed without merging**
