### PR TITLE
Revert "Hand Gesture Vehicle Control"

### PR DESCRIPTION
**Pull request by UTSAVS26**
Reverts UTSAVS26/PyVerse#78

@aviralgarg05 please check the image path too that you have given in the code they are not matching.

### CODE REVIEW

**Comment by aviralgarg05** [comment]
So should I create a separate PR to update the Readme.md?

**Comment by UTSAVS26** [comment]
> So should I create a separate PR to update the Readme.md?
> 

You need to rename the files again don't used double inverted in the names, use only understand and also update the code based on the update file names.

**Comment by UTSAVS26** [comment]
@aviralgarg05 and do this on urgent basis

**Comment by aviralgarg05** [comment]
I will do it asap

**Comment by UTSAVS26** [comment]
All the best 👍

**Pull request closed without merging**
