### PR TITLE
Add Project (Issue #16)

### PR DESCRIPTION
**Pull request by AHSANATIQ98**
# Pull Request for PyVerse 💡

## Issue Title: Add Number Guessing Game Project

- **Info about the related issue (Aim of the project)**: Adding a number guessing game project to help beginners practice Python programming.
- **Name:** Ahsan Atiq
- **GitHub ID:** AHSANATIQ98
- **Email ID:** ahsanatiq798@gmail.com
- **Identify yourself:** GSSoC Participant

Closes: #16

### Describe the add-ons or changes you've made 📃

Added a new Python project for a number guessing game. This project includes a Python script and a description text file explaining the purpose, usage, and dependencies.

## Type of change ☑️

What sort of change have you made:
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️

The project was tested by running the Python script multiple times to ensure it behaves as expected and provides accurate results. No errors or issues were encountered during testing.

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@AHSANATIQ98 have your assigned this project by me or by any mentors?

**Comment by TheChaoticor** [comment]
Can you say me in which directory your project in?

**Comment by UTSAVS26** [comment]
@AHSANATIQ98 I am closing this PR without merging. You need to first raise an issue and if me and any mentor approve it and assign you then only you can work on it.

**Review by UTSAVS26 — COMMENTED** [review]
**Invalid**

**Pull request closed without merging**
