### PR TITLE
GAN-based Art Generator

### PR DESCRIPTION
**Pull request by alo7lika**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
*GAN-based Art Generator.*

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The aim is to implement a Generative Adversarial Network (GAN) to generate synthetic artistic images that resemble real artworks.
*Describe the aim of the project.*

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Alolika Bhowmik*

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*alo7lika*

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*alolikabhowmik72@gmail.com*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*GSSoC*

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #914*

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*I have implemented a GAN model using TensorFlow and Keras that generates artistic images based on training data from various art styles. This includes preprocessing the dataset, defining the model architecture, and training the model.*

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*I tested the GAN model by generating images and validating them against the original dataset to check for visual similarity and artistic quality. The model training performance was also monitored using loss graphs.*

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by alo7lika** [comment]
@shaansuraj , @TheChaoticor , @ruhi47 Kindly review the PR

**Comment by UTSAVS26** [comment]
@alo7lika this file has no extension `Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image`

**Comment by UTSAVS26** [comment]
And also sync your repo as it has branch conflicts.

**Comment by alo7lika** [comment]
@UTSAVS26 check the PR . Solved all the Conflicts

**Pull request merged**
