### PR TITLE
Added TextSummarization Model, Continuation to PR #785

### PR DESCRIPTION
**Pull request by Peart-Guy**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
Text Summarization NLP Model

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
Python Project - People do face issues to summarize huge texts or students do face issues to learn huge texts. this model helps users to summarize those texts and use it according to their need, for example a learner can easily learn faster and understand the summarized text instead of going through huge paragraphs

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Ankan

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*Enter your GitHub ID here.*

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*Enter your email ID here.*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
GSSOC-24 EXTD

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
Closes: #753 

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
I have added a Text Summarization NLP model

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*Describe your testing process here.*

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Peart-Guy** [comment]
@UTSAVS26  
Kindly give Level 2. It will be an honor

**Comment by UTSAVS26** [comment]
> @UTSAVS26  
> Kindly give Level 2. It will be an honor

You are adding project that is counted under level1.

**Comment by Peart-Guy** [comment]
> > @UTSAVS26
> > Kindly give Level 2. It will be an honor
> 
> You are adding project that is counted under level1.


@UTSAVS26  Please give Level 2 as it take lot of effort and also other PA has given Level 2 for the same

WhatsApp Image 2024-10-27 at 20 04 49_54363161

**Comment by UTSAVS26** [comment]
> > > @UTSAVS26
> > > Kindly give Level 2. It will be an honor
> > 
> > You are adding project that is counted under level1.
> 
> 
> @UTSAVS26  Please give Level 2 as it take lot of effort and also other PA has given Level 2 for the same
> 
> WhatsApp Image 2024-10-27 at 20 04 49_54363161
> 

Send me the link of the PR.

**Comment by UTSAVS26** [comment]
Link?

**Comment by Peart-Guy** [comment]
> Link?

Sir , I asked why

**Comment by UTSAVS26** [comment]
> > Link?
> 
> Sir , I asked why 

I want to see the PR you are talking about related to level 2

**Comment by Peart-Guy** [comment]
> > > Link?
> > 
> > 
> > Sir , I asked why
> 
> I want to see the PR you are talking about related to level 2

https://github.com/yashasvini121/predictive-calc/pull/147

**Comment by UTSAVS26** [comment]
> > > > Link?
> > > 
> > > 
> > > Sir , I asked why
> > 
> > I want to see the PR you are talking about related to level 2
> 
> https://github.com/yashasvini121/predictive-calc/pull/147

That one is other repo not this one and this one.

**Comment by Peart-Guy** [comment]
> > > > > Link?
> > > > 
> > > > 
> > > > Sir , I asked why
> > > 
> > > 
> > > I want to see the PR you are talking about related to level 2
> > 
> > 
> > [yashasvini121/predictive-calc#147](https://github.com/yashasvini121/predictive-calc/pull/147)
> 
> That one is other repo not this one and this one.

I didn't understand what you said.
But Sir Kindly give level 2. as this is a code addition, and not a simple documentation

**Comment by UTSAVS26** [comment]
> > > > > > Link?
> > > > > 
> > > > > 
> > > > > Sir , I asked why
> > > > 
> > > > 
> > > > I want to see the PR you are talking about related to level 2
> > > 
> > > 
> > > [yashasvini121/predictive-calc#147](https://github.com/yashasvini121/predictive-calc/pull/147)
> > 
> > That one is other repo not this one and this one.
> 
> I didn't understand what you said.
> But Sir Kindly give level 2. as this is a code addition, and not a simple documentation 

The addition of any type of projects including advanced one in which deep learning or genai is used that also fall under level1 and if you fix any bug or add new feature that will be counted under level2 or level3.

**Pull request merged**
