### PR TITLE
Add Beginner-Level Python Projects

### PR DESCRIPTION
**Pull request by PasamTharun**
This is a simple egg-catching game built using Python and the Tkinter library. The player controls a catcher to catch falling eggs, scoring points for each successful catch while trying to avoid losing lives. The game increases in difficulty as time progresses.

# Pull Request for PyVerse 💡

## Issue Title : Add Beginner-Level Python Projects

- **Info about the related issue (Aim of the project)** : This is a simple egg-catching game built using Python and the Tkinter library. The player controls a catcher to catch falling eggs, scoring points for each successful catch while trying to avoid losing lives. The game increases in difficulty as time progresses.
- **Name:** Pasam Tharun
- **GitHub ID:**  PasamTharun
- **Email ID:** tpasamtharun@gmail.com
- **Idenitfy yourself: ** GirlScript Summer of Code 2024 Contributor

Closes: #58

### Describe the add-ons or changes you've made 📃

- Added a scoring system that tracks and displays the player's score in real-time.
- Implemented a lives system that deducts lives for each missed egg and ends the game when all lives are lost.
- Increased the difficulty of the game by adjusting the speed and frequency of falling eggs based on the player's score.

---
How it Works
Screenshot 2024-10-04 233143

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

## How Has This Been Tested? ⚙️

- The game has been tested for functionality, ensuring that the scoring and lives systems work as intended.
- Verified that the difficulty adjustments function correctly without causing game crashes or unexpected behavior.

---

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@PasamTharun please add proper comments for every function.

**Comment by PasamTharun** [comment]
Do mean in code???

**Comment by PasamTharun** [comment]
Do u mean in code??

**Comment by UTSAVS26** [comment]
Yes

**Comment by PasamTharun** [comment]
Done buddy

**Review by UTSAVS26 — APPROVED** [review]

**Review by TheChaoticor — APPROVED** [review]

**Pull request merged**
