### PR TITLE
House price prediction

### PR DESCRIPTION
**Pull request by Rahul-AkaVector**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
House Price Prediction #542

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The House Price Prediction project aims to develop a predictive model that estimates house prices based on various features such as location, size, number of bedrooms, and market trends. This algorithm will assist potential buyers in making informed decisions and help sellers price their properties competitively.

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Rahul-AkaVector

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
@Rahul-AkaVector 

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*rahul.aka.vector.dev@gmail.com*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
GSSOC, Hacktoberfest, level2

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
Closes: #542

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
I have implemented a machine learning model for house price prediction, which estimates house prices based on features such as location, size, number of bedrooms, and market trends. This includes adding a Streamlit-based web interface to allow users to input the required information and receive predictions in real-time.

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
I have tested the model and the Streamlit interface locally with various inputs to ensure that the predictions are accurate and the user interface functions as expected.

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Rahul-AkaVector** [comment]
@UTSAVS26 can u accept pull request and merge into main branch

**Comment by UTSAVS26** [comment]
> @UTSAVS26 can u accept pull request and merge into main branch 

Wait for sometime let mentors @shaansuraj and @TheChaoticor review it and approve.

**Comment by Rahul-AkaVector** [comment]
okay no problem

**Comment by Rahul-AkaVector** [comment]
@shaansuraj , @TheChaoticor review it plzzz

**Comment by ruhi47** [comment]
If the mentors are busy, I can dot it @UTSAVS26

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
I encountered some errors when i started the prediction.Please check

**Review by ruhi47 — APPROVED** [review]

**Pull request merged**
