### PR TITLE
Stock Prediction with CAPM and Fama-French Model 

### PR DESCRIPTION
**Pull request by sharayuanuse**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
Stock Prediction with CAPM and Fama-French Model 

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The goal of this project is to predict the stock returns of Mahindra using the Capital Asset Pricing Model (CAPM) and the Fama-French Three-Factor Model. The project aims to compare the accuracy of both models and determine which is better at predicting the company's stock returns based on historical financial data.

- [x] I have described the aim of the project.

---

#### Name
Sharayu Anuse

- [x] I have provided my name.

---

#### GitHub ID
114616759

- [x] I have provided my GitHub ID.

---

#### Email ID
sharayu.anuse@gmail.com
- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
GSSOC-Ext, Hacktoberfest

- [x] I have mentioned my participant role.

---

#### Closes

Closes: #250 

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
- Implemented both the CAPM and Fama-French Three-Factor Model for predicting stock returns.
- Added functionality for data analysis using Pandas and NumPy.
- Plotted visualizations to compare the predicted returns with actual returns using Matplotlib.
- Provided statistical analysis to demonstrate that the Fama-French model shows 36% greater accuracy than CAPM.

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
- Generated accuracy scores to compare the two models.
- Visualization Testing: Plotted data to visually verify the accuracy of predicted vs. actual stock returns.

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by sharayuanuse** [comment]
Can you please review and merge this issue.

**Comment by UTSAVS26** [comment]
> Can you please review and merge this issue.

Wait for some time as @shaansuraj and @TheChaoticor review it once, and if anyone approved then it will be merged.

**Comment by sharayuanuse** [comment]
Okay. Thank you.

**Comment by sharayuanuse** [comment]
@shaansuraj and @TheChaoticor can you review this pull request and merge it.

**Comment by sharayuanuse** [comment]
@UTSAVS26 can you review and merge the pull request.

**Pull request merged**
