### PR TITLE
Anomaly Detection in Time Series

### PR DESCRIPTION
**Pull request by alo7lika**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Anomaly Detection in Time Series**

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
To develop an effective model for detecting anomalies in time series data, leveraging LSTM networks for improved accuracy and reliability.  
*the project aims to create a robust solution for identifying anomalies in time series datasets, ultimately enhancing predictive capabilities in various applications.*

- [x] I have described the aim of the project.

---

#### Name
**Alolika Bhowmik**

- [x] I have provided my name.

---

#### GitHub ID
**alo7lika**

- [x] I have provided my GitHub ID.

---

#### Email ID
**alolikabhowmik72@gmail.com**

- [x] I have provided my email ID.

---

#### Identify Yourself
**GSSOC Contributor**  

- [x] I have mentioned my participant role.

---

#### Closes
**Closes: #913**  

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**I have implemented an LSTM model for detecting anomalies in synthetic time series data. The code includes data generation, model training, and performance evaluation with classification reports for comparison against other methods.**  

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [x] New feature (non-breaking change which adds functionality)

---

#### How Has This Been Tested?
**The model's performance was evaluated using classification reports, and results were plotted for visual inspection. The code was run successfully without errors, and accuracy metrics were generated to assess model performance.**  

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by alo7lika** [comment]
@UTSAVS26 the task has been completed. Kindly review the PR

**Comment by alo7lika** [comment]
@TheChaoticor , @ruhi47 , @shaansuraj kindly review the PR

**Comment by alo7lika** [comment]
@UTSAVS26

**Comment by UTSAVS26** [comment]
@alo7lika what is this file? `Deep_Learning/Anomaly Detection in Time Series/Images/Image`

**Pull request merged**
