### PR TITLE
Job scraper- Job data extraction tool from the web using Scrapy  #682

### PR DESCRIPTION
**Pull request by Niraj1608**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
Job scraper- Job data extraction tool from the web using Scrapy #682 

- [X] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The LinkedIn Job Scraper is a Python-based web scraping tool that uses Scrapy, a powerful web crawling framework, to extract job listings from LinkedIn. The tool is designed to circumvent common anti-scraping mechanisms like IP blocking by integrating proxy rotation, which ensures that the scraper can maintain a steady scraping speed while avoiding detection or throttling.

- [X] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Parmar Niraj

- [X] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
@Niraj1608

- [X] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
nirajprmr1608@gmail.com

- [X] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
GSSOC

- [X] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #682 

- [X] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
Scrapes job listings (job title, company, location, posting date, and description).
Uses proxies for IP rotation to avoid detection.
Allows the user to filter job results by keywords, locations, and other criteria.
Stores the scraped data in a structured format (e.g., CSV, JSON)

- [X] I have described my changes.

---

#### Type of Change
**Select the type of change:**  

- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  

- [X ] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [X ] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### screenshots

Screenshot 2024-10-16 194309

### CODE REVIEW

**Comment by Niraj1608** [comment]
@UTSAVS26 review my pr :))

**Comment by UTSAVS26** [comment]
@Niraj1608 link you issue correctly.

**Comment by Niraj1608** [comment]
@UTSAVS26 hey i update it can you check again

**Comment by Niraj1608** [comment]
@UTSAVS26 check my code , i think this project should get atleast level 2

**Pull request merged**
