### PR TITLE
Update KBCquiz.py

### PR DESCRIPTION
**Pull request by saanvi23454**
fixed issues with display (alligning lines to the right as well as left).

on quitting or wrong answer, correct answer also shown now

### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
fixed display, increased functionality

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
*Describe the aim of the project.*

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Saanvi S

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
saanvi23454

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
saanvisinghofficial@gmail.com

- [ ] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
GSSOC contributor

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #1122 *

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
Fixed * and - in display to align on the right as well
Added printing correct answer on quitting or wrong answer by user

- [ ] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ yes] New feature (non-breaking change which adds functionality)
- [ yes] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
visually

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by ruhi47 — APPROVED** [review]

**Comment by ruhi47** [comment]
@saanvi23454 mention the issue number. I couldn't find the issue, if not updated, I will close this issue.

**Review by ruhi47 — CHANGES_REQUESTED** [review]
No issue number mentioned in the PR. Please mention it or else I will have to close this.
@saanvi23454 .
Thanks!

**Comment by saanvi23454** [comment]
Didn't raise the issue I saw in the code before the corrections, is it ok to create now ? sorry about the confusion

**Comment by ruhi47** [comment]
@UTSAVS26 Please review this.

**Pull request closed without merging**
