### PR TITLE
Linked Lists

### PR DESCRIPTION
**Pull request by aviralgarg05**
# Pull Request for PyVerse 💡

## Issue Title :  Linked Lists

- **Info about the related issue (Aim of the project)** :   Linked lists are a fundamental data structure that allows efficient storage and manipulation of data and learn about it.
- **Name:**  Aviral Garg
- **GitHub ID:**  aviralgarg05
- **Email ID:**  gargaviral99@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)**  GSSOC 24' Extended

Closes: #issue number that will be closed through this PR
#7 
### Describe the add-ons or changes you've made 📃
Created a Linked Lists algorithm for Data Structures
Give a clear description of what have you added or modifications made
Created a Linked Lists algorithm for Data Structures
## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested: - Outputs have been clearly mentioned
Describe how have you verified the changes made:- Runtime and Correct outputs

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@aviralgarg05 please add comments in the code too in this format

'''python
def <function_name>(<parameters>):
    """
    <Brief description of the function's purpose.>

    Args:
        <parameter_name> (<parameter_type>): <Description of the parameter.>

    Returns:
        <return_type>: <Description of the return value.>

    Example:
        >>> <function_name>(<example_input>)
        <example_output>
    """
    # Function logic here
'''

**Comment by UTSAVS26** [comment]
@aviralgarg05 please add comments in the code too in this format

def <function_name>(<parameters>):
   
    <Brief description of the function's purpose.>

    Args:
        <parameter_name> (<parameter_type>): <Description of the parameter.>

    Returns:
        <return_type>: <Description of the return value.>

    Example:
        >>> <function_name>(<example_input>)
        <example_output>
   
    # Function logic here

**Review by UTSAVS26 — CHANGES_REQUESTED** [review]
Changes required

**Review by TheChaoticor — COMMENTED** [review]
Changes in comments required as suggested by the PA

**Comment by aviralgarg05** [comment]
Changes requested are made

**Review by UTSAVS26 — APPROVED** [review]

**Pull request merged**
