### PR TITLE
Clash of Space= A beautiful Space game developed in Python

### PR DESCRIPTION
**Pull request by Ashish-Patnaik**
## Pull Request for PyVerse 💡

This is a contribution to PyVerse under Game Development Folder

### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
   Issue number #648
**Please enter the title of the issue related to your pull request.**  
  A Space game made with python #648 

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
*Describe the aim of the project.*
A visually attractive Space game name "Clash in Space" developed using Pygame library in Python showing deep knowledge in Python

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Ashish Patnaik*

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*Ashish-Patnaik*

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*ashishpatnaik2806@gmail.com.*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*GSSOC.*

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #648*

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*A beautiful and visually attractive game made using Python with the help of Pygame library that entertains users to kill boring time*

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [x] New feature (non-breaking change which adds functionality)

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Ashish-Patnaik** [comment]
Kindly merge this PR @UTSAVS26 as this is a great help in boosting my confidence. Thank you sir

**Review by TheChaoticor — CHANGES_REQUESTED** [review]
Please check the paths

**Comment by Ashish-Patnaik** [comment]
what changes I have to do sir , I have correctly added the game in game development section without changing any other folders

**Comment by Ashish-Patnaik** [comment]
Now I have have changed and corrected everything in the game now please kindly merge this PR @TheChaoticor , @UTSAVS26 , @shaansuraj

**Pull request closed without merging**
