### PR TITLE
Create Auto-Label

### LINKED ISSUE #776: FEATURE :- Auto-label Workflow
**Description:**

I would like to request the addition of an **auto-label workflow** in this repository to automatically label pull requests with **"gssoc-ext"** and **"hacktoberfest-accepted"** during relevant events such as GSSoC (GirlScript Summer of Code) and Hacktoberfest.

### **Key Features:**
1. **Auto-label on PR Creation:**
   - Automatically apply the **"gssoc-ext"** label for any pull requests submitted as part of GSSoC.
   - Automatically apply the **"hacktoberfest-accepted"** label for pull requests during the Hacktoberfest period, or when contributors indicate Hacktoberfest participation.
   
2. **Workflow Automation:**
   - Use GitHub Actions to create a workflow that triggers upon pull request creation, checking the event or time period, and assigning the appropriate label automatically.
   
3. **Custom Conditions:** 
   - Allow maintainers to manually override the labels if necessary.
   - Include a check to ensure only valid PRs contributing to the project are labeled with **"hacktoberfest-accepted"**, following Hacktoberfest rules.

### **Benefits:**
- **Efficiency:** Automating this process will save time for maintainers by reducing manual labeling.
- **Transparency:** Ensures that contributors clearly know when their pull request has been accepted for relevant events.
- **Compliance:** Helps in staying aligned with the official rules for Hacktoberfest, where labels like **"hacktoberfest-accepted"** are required to validate contributions.

### **Suggested Implementation:**
- Add a GitHub Actions workflow file in `.github/workflows` that triggers on pull request events and applies the labels based on specific conditions.

Please @UTSAVS26 assign me this issue with labels"gssoc-ext", "hacktoberfest-accepted" and "level3"

### PR DESCRIPTION
**Pull request by archanasingh11**
fixed #776 
### Objective: 
Implement an "auto-label" GitHub workflow to automatically assign the "gssoc-ext" and "hacktoberfest-accepted" labels to relevant pull requests and issues.

### Details:

This workflow will streamline the labeling process by automatically applying the "gssoc-ext" and the "hacktoberfest-accepted" label to Issues.
By automating these labels, we can ensure consistent tracking and visibility of contributions tied to these significant events.
Implementing this "auto-label" workflow will enhance project organization

### CODE REVIEW

**Comment by archanasingh11** [comment]
Hey @UTSAVS26 I have raised PR
Thanks

**Comment by archanasingh11** [comment]
If you find worth it Do upgrade my level

**Comment by archanasingh11** [comment]
Hey @UTSAVS26 do assign me the Labels in the PR also or else My contribution wont be counted

**Comment by UTSAVS26** [comment]
> Hey @UTSAVS26 do assign me the Labels in the PR also or else My contribution wont be counted

I have added the labels already before merging.

**Pull request merged**
