### PR TITLE
Added Red Wine Quality detection 

### PR DESCRIPTION
**Pull request by inkerton**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
*Red wine Quality Detection*

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
Red wine Quality Detection by statisticall addressing and referencinf each of these features 'residual sugar', 'total sulfur dioxide', 'sulphates', 'alcohol', 'volatile acidity', 'quality' and then thoroughly taking out a decision on the overall quality. 

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Janvi
- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
[inkerton](https://github.com/inkerton)
- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
janvichoudhary116@gmail.com

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
GSSOC

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #issue-number* #301

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
I have added these 7 models and evaluated their accuracy 
- **Logistic Regression (LR):** A linear model that predicts categorical outcomes based on input features.
- **Naive Bayes (NB):** A probabilistic model based on Bayes’ theorem.
- **K-Nearest Neighbors (KNN):** A non-parametric model that classifies based on the majority vote of the nearest neighbors.
- **Decision Tree (DT):** A tree-based model that splits the data on feature values to predict the target variable.
- **Support Vector Machine (SVM):** A model that finds the optimal hyperplane to classify data points in high-dimensional spaces.
- **Linear Discriminant Analysis (LDA):** A linear model that reduces dimensionality while preserving as much class-discriminatory information as possible.
- 
- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
The project has been tested using the following methods:

1. **Cross-Validation:** 
   - 5-fold Stratified Cross-Validation was used to evaluate the performance of each machine learning model. This ensures that the model is tested on different subsets of the data, providing a robust evaluation of its accuracy.

2. **Model Evaluation Metrics:**
   - Each model was evaluated using accuracy scores, which were calculated during cross-validation. This allowed comparison of the success rates of various models like Logistic Regression, K-Nearest Neighbors, Decision Tree, etc.

3. **Handling Class Imbalance:**
   - The dataset's imbalanced nature was addressed using SMOTE, which oversamples minority classes, ensuring that models perform well across all wine quality levels.
- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by inkerton** [comment]
@UTSAVS26 

**I would like the difficulty of this issue to be raised to level3 if you see fit.** 
## Reasoning for Reclassification:
**Multiple Model Evaluation:** Evaluating seven different models requires understanding each model's strengths and weaknesses, as well as comparing their performance across the same dataset. This increases the effort and knowledge required, as the results must be analyzed, interpreted, and reported for multiple models.

**Cross-Validation:** Stratified K-Fold cross-validation for all models, rather than simple train-test splits, ensures that the models are tested rigorously. This adds both complexity and a significant time investment to the project.

**Handling Imbalanced Data:** Using SMOTE to address class imbalance adds another layer of difficulty, as it involves advanced preprocessing techniques to ensure model fairness across all wine quality categories.

SMOTE (Synthetic Minority Over-sampling Technique) is a technique used in machine learning to handle imbalanced datasets. When you have a classification problem where one class is significantly underrepresented compared to others (imbalanced data), models can become biased towards the majority class, leading to poor performance on the minority class.

**Comment by UTSAVS26** [comment]
@inkerton please go through the discussion announcement section, based on the rules if anyone is adding any project it will be categorised into level1 until they are fixing any bug or adding feature to it, but as the issue is already been assigned to `level2` before making the announcement that's why I didn't change it.

**Comment by inkerton** [comment]
@UTSAVS26  So adding a project of any complexity will now be categorized as level1??

**Comment by inkerton** [comment]
@UTSAVS26 I have a minor specialization in data science and have many projects which are incomplete like they have the model but I have worked on explaining the result any plots or any explainatory code to explain the result. They just have they result declared as accuracy = this or like that .

I was thinking of completing them and then adding them here so should i just add them first and the add features and algorithms to them? Don't mind but I also have to earn points and if i can work on my own projects and earn points that would be beneficial to me.

**Review by shaansuraj — APPROVED** [review]

**Comment by UTSAVS26** [comment]
> @UTSAVS26  So adding a project of any complexity will now be categorized as level1?? 

Yes

**Pull request merged**
