### PR TITLE
Add Update structure workflow

### PR DESCRIPTION
**Pull request by yashksaini-coder**
This pull request introduces a script to automatically update the repository structure and a corresponding GitHub Actions workflow to run the script periodically. Additionally, it updates the `README.md` and `repo_structure.txt` files to reflect the new structure. The most important changes include the addition of the update script, the creation of the workflow, and the updates to the documentation files.

### Automation and Scripting:

* [`.github/scripts/update_dir_structure.py`](diffhunk://#diff-a3513e00160838e62e57ce600bce7b0601df6ea27e8f1f89c23109b06b3aca7dR1-R67): Added a Python script to generate the repository structure, update `repo_structure.txt`, and modify the `README.md` with the new structure.

### Workflow Configuration:

* [`.github/workflows/update-structure.yml`](diffhunk://#diff-5b5facd8bb90fc1694247fa0b5a50785d84b01b99b9d0143b4c50336ae8301bcR1-R39): Created a GitHub Actions workflow to run the update script every hour, on push events to specific branches, and manually.

### Documentation Updates:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R75-R95): Updated the repository structure section to use markers and dynamically insert the structure generated by the script.
* [`repo_structure.txt`](diffhunk://#diff-8a8cbb4a03394f5a83d1c484fc0a9108453d8a07ff0fc1df80c6d6a6aa0862a9R1-R17): Updated to reflect the current directory structure of the repository.# Pull Request for PyVerse 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Yash K. Saini
- **GitHub ID:** yashksaini-coder
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)** WoB'24 Participant

Closes: #4 

### Describe the add-ons or changes you've made 📃

- GitHub actions workflow to update the repo structure as it expands. 
- Runs every hour
- Updates as new files are added ☑️

| Before       | After        |
|--------------|--------------|
| Before Image | After Image |

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested

- Ran in my own branch, till it generated the desired result. Achieved breakthrough after 4 workflow runs.

image

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@UTSAVS26  Review & add label `Level3` to this PR.

**Comment by UTSAVS26** [comment]
> @UTSAVS26  Review & add label `Level3` to this PR. Also add to the issue #4 too.


@yashksaini-coder please reorder the project structure like a way in which all the folders come on top with the `/` at last to show that these are folders and all the single files at last

**Comment by yashksaini-coder** [comment]
@UTSAVS26 As you can see the changes below the project structure is automatically updated after I add a basic **Data-science.md** This will be the same to all the files that are uploaded inside other folders. Also the workflow is designed to detect any incoming changes or commits & trigger to execute the **update-structure.py** python script.

It can also reformat the Project structure if a subfolder is also stored inside the main root folders.



| Before       | After        |
|--------------|--------------|
| Before Image | After Image |

**Comment by UTSAVS26** [comment]
@yashksaini-coder good work I am changing the level from `level1` to `level2`

**Review by UTSAVS26 — APPROVED** [review]

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder good work I am changing the level from `level1` to `level2`

why not `level3` ?

**Comment by UTSAVS26** [comment]
@yashksaini-coder I will merge your PR after sometime as it showing some error at my side when it is done I will close the pr automatically you can work other issues till then.
Best of Luck 🍀

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder I will merge your PR after sometime as it showing some error at my side when it is done I will close the pr automatically you can work other issues till then. Best of Luck 🍀

oh also you need to create a github token and add it in the secrets. It gives the script access to the root dir

**Comment by UTSAVS26** [comment]
> > @yashksaini-coder I will merge your PR after sometime as it showing some error at my side when it is done I will close the pr automatically you can work other issues till then. Best of Luck 🍀
> 
> oh also you need to create a github token and add it in the secrets. It gives the script access to the root dir

I will look into it thanks for the advice.

**Comment by yashksaini-coder** [comment]
There are no conflicts showing with the main branch. so everything will be all good. 👍🏼 

I think this issue could use `level3`

**Comment by UTSAVS26** [comment]
> There are no conflicts showing with the main branch. so everything will be all good. 👍🏼 
> 
> I think this issue could use `level3`

I will check it once then update the level otherwise it definitely covers `level2`

**Comment by yashksaini-coder** [comment]
> > There are no conflicts showing with the main branch. so everything will be all good. 👍🏼
> > I think this issue could use `level3`
> 
> I will check it once then update the level otherwise it definitely covers `level2`

while you are at it, can you add `hacktoberfest-accepted` label

**Comment by UTSAVS26** [comment]
> > > There are no conflicts showing with the main branch. so everything will be all good. 👍🏼
> > > I think this issue could use `level3`
> > 
> > I will check it once then update the level otherwise it definitely covers `level2`
> 
> while you are at it, can you add `hacktoberfest-accepted` label

We are given strict guidelines to only add `hacktoberfest-accepted` labels for only GSSOC'24-Extd. Contributors. Sorry for your trouble

**Comment by yashksaini-coder** [comment]
> > > > There are no conflicts showing with the main branch. so everything will be all good. 👍🏼
> > > > I think this issue could use `level3`
> > > 
> > > 
> > > I will check it once then update the level otherwise it definitely covers `level2`
> > 
> > 
> > while you are at it, can you add `hacktoberfest-accepted` label
> 
> We are given strict guidelines to only add `hacktoberfest-accepted` labels for only GSSOC'24-Extd. Contributors. Sorry for your trouble

okh

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you add gssoc label in this PR & assign it to me.

**Comment by yashksaini-coder** [comment]
hi @UTSAVS26 can you add gssoc & hacktoberfest labels on this PR, and assign it to me

**Comment by UTSAVS26** [comment]
@yashksaini-coder let me ask program manager if it is possible.

**Pull request merged**
