### PR TITLE
Implemented Apriori and Association Rule Mining for Intrusion Detection System.

### PR DESCRIPTION
**Pull request by IkkiOcean**
#### Issue Title
Intrution Detection System using Association Rule Mining.
- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The goal of the project is to develop an Intrusion Detection System that utilizes Apriori and association rule mining techniques to identify potential threats and anomalies in network traffic.

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Vivek Prakash

- [x] I have provided my name.

---

#### GitHub ID
 
 https://github.com/IkkiOcean

- [x] I have provided my GitHub ID.

---

#### Email ID
 - vivekprakash.st@gmail.com

- [x] I have provided my email ID.

---

#### Identify Yourself
GSSOC-ext and hacktoberfest

- [x] I have mentioned my participant role.

---

#### Closes
Closes: #437 

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made

- Created rules using Apriori and association rule mining to enhance the Intrusion Detection System.
- Added the dataset and notebooks necessary for running the project.
- Improved documentation with detailed feature descriptions.

- [x] I have described my changes.

---

#### Type of Change
- [x] New feature (non-breaking change which adds functionality)

---

#### Checklist
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by IkkiOcean** [comment]
Request: This is not documentation only, provide level 2 please

**Comment by IkkiOcean** [comment]
kindly review @UTSAVS26

**Comment by IkkiOcean** [comment]
Please atleast provide level 2 since this is not only documentation.

**Comment by IkkiOcean** [comment]
@shaansuraj  please review. I have been waiting and do consider raising the level

**Comment by UTSAVS26** [comment]
And sorry i cant give level2 to this project. If you do any bug fixing or add new feature in existing codebase then it will be counted in level2 or higherm

**Pull request merged**
