### PR TITLE
Addition of Testimonials Slider and Course Catalog Project | Issue #338

### PR DESCRIPTION
**Pull request by Shariq2003**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
Addition of Testimonials Slider and Course Catalog Project | Issue #338

- [X] I have provided the issue title.

---

#### Name
**Please mention your name.**  
*Enter your name here.*
Shariq
- [X] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*Enter your GitHub ID here.*
Shariq2003
- [X] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*Enter your email ID here.*

- [ ] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*Enter your participant role here.*
GSSOC Ext
- [X] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #338 
- [X] I have provided the issue number.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### Checklist
**Please confirm the following:**  
- [X] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] ] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Shariq2003** [comment]
@UTSAVS26 please merge this.

**Comment by Shariq2003** [comment]
@UTSAVS26 please review this PR,
This is in pending state since last 3 days.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 please review this PR,
> This is in pending state since last 3 days.

Sorry for the inconvenience from my side. I will review it rn.

**Comment by UTSAVS26** [comment]
@Shariq2003 sorry but this project is not going to add on as you are not using any python scripts as i am also removing some projects that don't have python integrated in them. 
Sorry for your time and efforts.

**Pull request closed without merging**
