### PR TITLE
Project Add: Lead case study model

### PR DESCRIPTION
**Pull request by yashksaini-coder**
### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title
**Please enter the title of the issue related to your pull request.**  
#860 
- [X] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
Adding a Lead case study project that shows the different techniques which we can use to analyze the proper sales, with the different visualizations that allows us to see data analysis of various different factors & growths.
- [X] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Yash K. Saini

- [X] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
[yashksaini-coder](https://github.com/yashksaini-coder)

- [X] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*Enter your email ID here.*

- [ ] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
GSSoC-Ext

- [X] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
#860
 
- [X] I have provided the issue number.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
I tested and generated plots

- [X] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@yashksaini-coder remove plus sign from the file name.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder remove plus sign from the file name. 

I don't see a plus sign, which file u talking about ?

**Comment by UTSAVS26** [comment]
`Data_Science/Lead Conversion Case Study/EDA+Feature Engineering+Outlier Analysis.ipynb`

**Comment by yashksaini-coder** [comment]
@UTSAVS26 bro done with the changes you can merge it now

**Pull request merged**
