### PR TITLE
Digital Image Tampering Detection Issue #305

### PR DESCRIPTION
**Pull request by thejatingupta7**
# Pull Request for PyVerse 💡

## Issue Title : 📃: Digital Image Tampering Detection Issue #305

- **Info about the related issue (Aim of the project)** :   To classify If the image is tampered(edited) or not. And also, to predict the area where it is tampered!
- **Name:**  Jatin Gupta
- **GitHub ID:**  thejatingupta7
- **Email ID:**  jatingupta261001@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a WoB 2024 participant it's, `WoB Participant`)** 
GSSOC 
Hacktoberfest

Closes: #issue number that will be closed through this PR #305

### Describe the add-ons or changes you've made 📃

This project focuses on detecting digital image tampering using the CASIA dataset using CNN. The CASIA dataset is a comprehensive collection of images used for research in image forensics.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

This project focuses on detecting digital image tampering using the CASIA dataset using CNN. The CASIA dataset is a comprehensive collection of images used for research in image forensics.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@thejatingupta7 there is no file in PR.

**Comment by thejatingupta7** [comment]
Actually my previous PR added this project as well! So i had to delete it and re add it to create this PR.

**Comment by UTSAVS26** [comment]
> Actually my previous PR #317 added this project as well! So i had to delete it and re add it to create this PR. 

But still there is no file in this PR.

**Comment by thejatingupta7** [comment]
image
This is added!

**Comment by UTSAVS26** [comment]
> image
> This is added!

It is being added in your repo not in main.

**Comment by UTSAVS26** [comment]
If your previous project has already been merged so why you raised same PR again?

**Pull request closed without merging**
