### PR TITLE
Add web development resources

### PR DESCRIPTION
**Pull request by Charul00**
# Pull Request for PyVerse 💡

## Issue Title : Web Development Resources PDF

- **Info about the related issue (Aim of the project)** : The aim of this project is to provide a detailed PDF that compiles essential resources for learning web development. It includes tutorials, documentation, tools, and frameworks necessary for both beginners and advanced developers to enhance their web development skills.
- **Name:** Charul Chim
- **GitHub ID:** Charul00
- **Email ID:** charulchim@example.com
- **Identify yourself:** gssoc 2024 Participant

Closes: #134 

### Describe the add-ons or changes you've made 📃

I have added a comprehensive PDF document containing a curated list of web development resources. The PDF includes categories such as HTML, CSS, JavaScript, frontend frameworks (e.g., React, Vue), backend technologies (e.g., Node.js, Express), and tools for deployment and testing.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested all the links and references within the PDF to ensure they are active and provide relevant information. Additionally, the content was reviewed for clarity and usability.

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by UTSAVS26 — CHANGES_REQUESTED** [review]
Please rename all the files into the standard naming convention like `book_name_1` and `book_name_2`.

**Comment by Charul00** [comment]
@UTSAVS26  Web Design Basics_1 like this ?

**Comment by UTSAVS26** [comment]
> @UTSAVS26  Web Design Basics_1 like this ?
> 

`Web_Design_Basics_1`
If you multiple files names `Web_Design_Basics` then only add number to them otherwise don't do it.

**Comment by Charul00** [comment]
> Please rename all the files into the standard naming convention like `book_name_1` and `book_name_2`.

can you give me example for that

**Comment by UTSAVS26** [comment]
> > Please rename all the files into the standard naming convention like `book_name_1` and `book_name_2`.
> 
> can you give me example for that 
> 
> 

Like you have files 2 files named same and basically are parts like 1st part and 2nd part you can give them name like that 'PyVerse_1` and `PyVerse_2`

**Comment by Charul00** [comment]
but in my files each file name is different

**Comment by UTSAVS26** [comment]
> @UTSAVS26 but in my files each file name is different name like we are saying for folder ?

So you can name as as before but with underscore.

**Comment by Charul00** [comment]
ok

**Pull request closed without merging**
