### PR TITLE
Economic Regime Detection

### PR DESCRIPTION
**Pull request by alo7lika**
# Pull Request for PyVerse 💡

## Issue Title: Economic Regime Detection

- **Info about the related issue (Aim of the project)**: Economic Regime Detection involves identifying distinct phases in the financial markets, such as bull (rising prices) and bear (declining prices) markets, to aid traders and investors in making informed decisions. The process begins with collecting historical price data and relevant market indicators, followed by feature engineering to calculate daily returns, technical indicators, and volatility measures. Data preprocessing, including normalization and handling missing values, ensures the dataset is ready for analysis. Clustering techniques like K-means, hierarchical clustering, or DBSCAN are then applied to categorize historical price movements into different regimes, with subsequent analysis to label these clusters as bull, bear, or neutral markets based on their characteristics. To predict future market regimes, a regime-switching model or supervised learning methods can be employed. Finally, the model's effectiveness is validated through backtesting against historical data, and visualizations are created to illustrate the identified market phases, ultimately enhancing trading strategies and decision-making based on the current market environment.

- **Name:** Alolika Bhowmik
- **GitHub ID:** https://github.com/alo7lika
- **Email ID:** alolikabhowmik72@g-mail.com
- **Identify yourself**: GSSOC Participant

Closes: # (issue number that will be closed through this PR) #209

### Describe the add-ons or changes you've made 📃

In this PR, I have implemented the Economic Regime Detection project, which includes the following changes:
- Collected and preprocessed historical price data and relevant market indicators.
- Engineered features to calculate daily returns, technical indicators, and volatility measures.
- Applied clustering techniques (K-means) to categorize price movements into different regimes.
- Developed a regime-switching model for predicting future market conditions.
- Validated the model through backtesting and created visualizations to illustrate market phases.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested the implementation using historical financial data, ensuring that:
- The feature engineering process accurately calculates daily returns and indicators.
- Clustering techniques successfully categorize historical data into distinct market regimes.
- The regime-switching model provides reliable predictions for future market conditions.
- Backtesting results validate the model's effectiveness against historical data.

To reproduce the tests, run the included Jupyter notebook with the dataset provided in the repository.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by alo7lika** [comment]
@UTSAVS26

**Comment by UTSAVS26** [comment]
> @UTSAVS26 

Yes

**Comment by UTSAVS26** [comment]
> > > @UTSAVS26
> > 
> > Yes
> 
> I have checked the files are present.

Connect with me on discord.

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad review this PR

**Review by MastanSayyad — COMMENTED** [review]
readme changes, updating to level 1

**Comment by alo7lika** [comment]
> readme changes, updating to level 1

This isn't README changes this is a project

**Comment by MastanSayyad** [comment]
@alo7lika It is for both. read the guidelines 

Both project additions and readme changes are level 1 contributions as anyone can copy and paste it from internet 

image

**Pull request merged**
